Traceback (most recent call last):
  File "/home/chris/.virtualenvs/soccerdata/bin/gunicorn", line 8, in <module>
    load_entry_point('gunicorn==0.12.0', 'console_scripts', 'gunicorn')()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 32, in run
    WSGIApplication("%prog [OPTIONS] APP_MODULE").run()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 129, in run
    self.configure_logging()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 148, in configure_logging
    handlers.append(logging.FileHandler(self.cfg.logfile))
  File "/usr/lib/python2.6/logging/__init__.py", line 819, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.6/logging/__init__.py", line 838, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/chris/www/soccer-data/logs/gunicorn.log'
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/soccerdata/bin/gunicorn", line 8, in <module>
    load_entry_point('gunicorn==0.12.0', 'console_scripts', 'gunicorn')()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 32, in run
    WSGIApplication("%prog [OPTIONS] APP_MODULE").run()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 129, in run
    self.configure_logging()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 148, in configure_logging
    handlers.append(logging.FileHandler(self.cfg.logfile))
  File "/usr/lib/python2.6/logging/__init__.py", line 819, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.6/logging/__init__.py", line 838, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/chris/www/soccer-data/logs/gunicorn.log'
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/soccerdata/bin/gunicorn", line 8, in <module>
    load_entry_point('gunicorn==0.12.0', 'console_scripts', 'gunicorn')()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 32, in run
    WSGIApplication("%prog [OPTIONS] APP_MODULE").run()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 129, in run
    self.configure_logging()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 148, in configure_logging
    handlers.append(logging.FileHandler(self.cfg.logfile))
  File "/usr/lib/python2.6/logging/__init__.py", line 819, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.6/logging/__init__.py", line 838, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/chris/www/soccer-data/logs/gunicorn.log'
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/soccerdata/bin/gunicorn", line 8, in <module>
    load_entry_point('gunicorn==0.12.0', 'console_scripts', 'gunicorn')()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 32, in run
    WSGIApplication("%prog [OPTIONS] APP_MODULE").run()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 129, in run
    self.configure_logging()
  File "/home/chris/.virtualenvs/soccerdata/lib/python2.6/site-packages/gunicorn/app/base.py", line 148, in configure_logging
    handlers.append(logging.FileHandler(self.cfg.logfile))
  File "/usr/lib/python2.6/logging/__init__.py", line 819, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.6/logging/__init__.py", line 838, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/chris/www/soccer-data/logs/gunicorn.log'
